name: Docker

on:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE
      - '**.md'
    branches:
      - master
      - dev

  release:
    types:
      - published

env:
  IMAGE_NAME: ghcr.io/slashnephy/feedchime

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image tag (master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV
      - name: Prepare image tag (dev)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: echo "DOCKER_TAG=dev" >> $GITHUB_ENV
      - name: Prepare image tag (Release)
        if: github.event_name == 'release'
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
